### ISSUE TITLE
 Implement Random Greeting Messages

### ISSUE THREAD

**Issue by methmiranasinghe** [methmiranasinghe/Hacktober-Fest#11]
Modify the greeting in the random_greeting.py to display a random greeting message from a predefined list of messages.
greetings = ["Hello", "Hi there", "Hey", "Greetings"]
Give Greeting messages in different languages

**Comment by MarcelFox** [comment]
Which list of messages? Any nice massages or something else such as, different languages and so forth?

**Comment by jayeshs08** [comment]
Hey @methmiranasinghe can you assign this issue to me please?

**Comment by Aditi22Bansal** [comment]
Kindly assign this issue to me

**Comment by methmiranasinghe** [comment]
done
