### ISSUE TITLE
Implement Basic User Authentication

### ISSUE THREAD

**Issue by methmiranasinghe** [methmiranasinghe/Hacktober-Fest#6]
Create a basic user authentication system where the user has to enter a predefined username and password to access the application use the user_authentication.py file

**Comment by Tarunkumarchelumalla** [comment]
I want to contribute in the issue assign this to me @methmiranasinghe

**Comment by Tarunkumarchelumalla** [comment]
completed the userAuthentication
And some essential readme changes
please look into this pr:-https://github.com/methmiranasinghe/Hacktober-Fest/pull/15 @methmiranasinghe

**Comment by methmiranasinghe** [comment]
done

**Comment by Tarunkumarchelumalla** [comment]
Thank you
